# 이 파일은 특정 모듈에 소속된 엔티티의 특성에 대한 정의를 서술함.
# entities:
#   product:
#     fields:
#       status:
#         domain: Status
#       slug:
#         domain: "Slug(220)"
#       brand_id:
#         fk:
#           on_delete: SET NULL
#           on_update: CASCADE
#     indexes:
#       - columns: [status, product_id]
#         unique: false

# indexes:
#   - table: product_variant
#     columns: [sku]
#     unique: true