@startuml usecase
left to right direction

actor "관리자" as admin

usecase "상품 목록" as UC_LIST
usecase "특별 상품 목록" as UC_SPECIAL_LIST
usecase "특별 상품 등록" as UC_SPECIAL_INSERT
usecase "특별 상품 수정" as UC_SPECIAL_MODIFY
usecase "특별 상품 승인" as UC_SPECIAL_APPROVAL
usecase "특별 상품 상태변경" as UC_SPECIAL_STATUS
usecase "상품 상세" as UC_DETAIL
usecase "상품 승인" as UC_APPROVAL
usecase "상품 상태변경" as UC_STATUS

admin --> UC_LIST : 목록 요청\n(정상진입)
admin --> UC_DETAIL : 상세 요청\n(목록 -> 상세 or 광고진입)
admin --> UC_SPECIAL_LIST : 특별 목록 요청\n(추천 등 의도가 있는 목록)
admin --> UC_SPECIAL_INSERT : 특별 목록 등록 요청\n(추천 등 의도가 있는 목록)
admin --> UC_SPECIAL_MODIFY : 특별 목록 수정 요청\n(추천 등 의도가 있는 목록)
admin --> UC_SPECIAL_APPROVAL : 특별 목록 승인 요청\n(추천 등 의도가 있는 목록)
admin --> UC_SPECIAL_STATUS : 특별 목록 상태 변경 요청\n(추천 등 의도가 있는 목록)
admin --> UC_APPROVAL : 승인 요청
admin --> UC_STATUS : 상태 변경 요청
@enduml